### ISSUE TITLE
Library challenges

### ISSUE THREAD

**Issue by alexilyaev** [500tech/shredderjs#3]
I've read the design doc, nice!

I think we can't use Angular 2 if we're building a library.
But we can use TypeScript since it compiles to ES5.

I'm thinking it should be as lightweight as possible.
I'd go for building a flat design ourselves with Flexbox and CSS3 stuff.
That means dropping IE9 support, I don't think we should support it anyway.

**Comment by morsdyce** [comment]
Thanks!

I was toying with the idea of exporting 2 separate packages from the library.

you could require 'shredderjs/api' to only include the programmatic interface
and you could require 'shredderjs' to include the UI package as well.

need to test it out if its feasible.
But in that case it doesn't matter which frontend framework we use since its transparent to the user (we inject ourselves to the page without him needing to configure anything).
which should work with any framework.

If we use flexbox we might have to drop IE10 too unless prefixer knows how to deal with the conversion to the old flexbox model and hope we don't hit any edge cases (we probably will).

I think the simplest solution would be to use bootstrap along with a custom theme that we'll create (or slightly modify) which will make it work anywhere and will generate less work until we are ready for a serious design revision.

**Comment by alexilyaev** [comment]
Are we going to support loading the library as plain `<script>` tags?
How would the split libraries work in that case?

Autoprefixer handles it well, I don't think it's an issue.
The problem with loading 3rd party CSS is that it affects the whole page, unless there's a way to prefix all of Bootstrap in the custom build.

**Comment by morsdyce** [comment]
I'm pretty sure you can add prefix to bootstrap classes via scss, all of our css should be prefixed either way.

Currently I setup webpack to output as a commonjs library (it supports <script> tags as well).
I think we can generate 2 bundle files, 1 with everything and 1 with just the API part.
But don't take my word for it, need to test it out.

**Comment by alexilyaev** [comment]
So we need to check if we can add Bootstrap with custom prefix to all of it's CSS.

**Comment by morsdyce** [comment]
Just to update, I've researched if we can use bootstrap in a way that will never bother the end user or us and it seems the answer is no.

I guess we'll just have to use custom css
